version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    platform: linux/amd64
    environment:
      POSTGRES_DB: app_dev
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5430:5432"

  web:
    platform: linux/amd64
    build: .
    command: [
      "bundle",
      "exec",
      "rails",
      "server",
      "-b",
      "0.0.0.0"
    ]
    environment:
      REDIS_URL: "redis://redis:6379/12"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/spa-clone
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true

  redis:
    image: redis
    platform: linux/amd64
    container_name: spa_clone_redis
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - '6380:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db-data:
  bundle:
